<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $_SESSION['user']['locale']; ?>" class="hl-<?php echo $_SESSION['user']['locale']; ?> logged-in ">
<head>
    <meta charset="UTF-8" />
    <title>Edit Profile &bull; <?php echo SITE_NAME; ?></title>

    <meta name="robots" content="noimageindex" />

    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo BASEURL; ?>/images/favicon.ico" />


    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />



        <script type="text/javascript" src="<?php echo BASEURL; ?>/js/jquery.js"></script>
        <script type="text/javascript" src="<?php echo BASEURL; ?>/js/bluebar.js"></script>

        <script type="text/javascript">
            __DEV__ = false;
            window._jscalls = [];
        </script>


    <script type="text/javascript" src="<?php echo BASEURL; ?>/js/polyfills-build/polyfill_modern.js"></script>
    <script data-main="<?php echo BASEURL; ?>/js/modules-build/main.js" src="<?php echo BASEURL; ?>/js/require.js"></script>
    <script type="text/javascript" src="<?php echo BASEURL; ?>/js/strings/strings_en.js"></script>




    <script type="text/javascript" src="<?php echo BASEURL; ?>/js/navigation.js"></script>



    <link rel="stylesheet" type="text/css" href="<?php echo BASEURL; ?>/css/public/accounts-main.css"/>


</head>
<body class="sidebar-page">

<div class="root">


    <div class="page">

        <header class="top-bar">
            <div class="wrapper">
                <hgroup>
                    <h1 class="logo"><a href="<?php echo BASEURL; ?>"><?php echo SITE_NAME; ?></a></h1>

                </hgroup>



                <div class="account-state">
                    <ul class="actions">


                        <li id="link_profile" class="link-profile has-dropdown">
                            <a href="javascript:;">

    <span class="img img-outset current-user-avatar" style="background-image: url(<?php echo BASEURL; ?>/images/profiles/anonymousUser.jpg);">
        <img src="<?php echo BASEURL; ?>/images/profiles/anonymousUser.jpg" onerror="imageFallback(this);" alt="" />
        <b></b>
    </span>

                                <strong><?php echo $_SESSION['user']['username']; ?></strong>
                            </a>

                            <div class="dropdown">
                                <i></i>

                                <ul>
                                    <li><a href="<?php echo BASEURL; ?>/<?php echo $_SESSION['user']['username']; ?>">View Profile</a></li>
                                    <li><a href="<?php echo BASEURL; ?>/accounts/edit/">Edit Profile</a></li>
                                    <li><a href="<?php echo BASEURL; ?>/accounts/badges/">Badges</a></li>
                                    <li><a href="<?php echo BASEURL; ?>/accounts/logout/">Log Out</a></li>
                                </ul>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </header> <!-- .top-bar -->



    <div class="sidebar">
        <div class="wrapper">
            <nav class="sidebar-nav">
                <div class="sidebar-content">

    <h2><i></i>Your Account<span class="separator"> &bull; </span><span class="subtitle"></span></h2>
    <ul>
        <li class="active">
        <a href="<?php echo BASEURL; ?>/accounts/edit/">

            Edit Profile

            <i class="disclosure"></i>

        </a>

    </li>
        <li >
        <a href="<?php echo BASEURL; ?>/accounts/password/change/">

            Change Password

            <i class="disclosure"></i>

        </a>

    </li>
        <li >
        <a href="<?php echo BASEURL; ?>/accounts/manage_access">

            Manage Applications

            <i class="disclosure"></i>

        </a>

    </li>
        <li >
        <a href="<?php echo BASEURL; ?>/accounts/badges/">

            Badges

            <i class="disclosure"></i>

        </a>

    </li>
        <li >
        <a href="<?php echo BASEURL; ?>/accounts/logout/">

            Log Out

        </a>

    </li>
    </ul>

                </div>
            </nav>
        </div>
    </div>
    <div class="main">
        <div class="wrapper">
            <section class="nav-page-content" role="main">

    <header>
    <h1>Edit Profile</h1>
    </header>






<form  method="POST" accept-charset="utf-8" class="adjacent bordered">


   <input type="hidden" name="csrfmiddlewaretoken" value="<?php echo sha1( $_SESSION['user']['id'] ); ?>" />





    <p class="form-text">
        <label>Name</label>
        <span><input name="first_name" autocorrect="off" value="<?php echo $_SESSION['user']['first_name']; ?>" maxlength="30" type="text" id="id_first_name" /></span>
    </p>


    <p class="form-text">
        <label>Email</label>
        <span><input type="email" name="email" value="<?php echo $_SESSION['user']['email']; ?>" id="id_email" /></span>
    </p>


    <p class="form-text">
        <label>Username</label>
        <span><input name="username" maxlength="30" autocapitalize="off" autocorrect="off" type="text" id="id_username" value="<?php echo $_SESSION['user']['username']; ?>" /></span>
    </p>


    <p class="form-text">
        <label>Phone Number</label>
        <span><input type="tel" name="phone_number" id="id_phone_number" /></span>
    </p>


    <p class="form-select">
        <label>Sex</label>
        <span><select name="gender" id="id_gender">
<option value="3" selected="selected">--------</option>
<option value="1">Male</option>
<option value="2">Female</option>
</select></span>
    </p>


    <p class="form-select form-select-multi">
        <label>Birthday</label>
        <span><select name="birthday_month" id="id_birthday_month">
<option value="0">---</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option>
</select>
<select name="birthday_day" id="id_birthday_day">
<option value="0">---</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>
<select name="birthday_year" id="id_birthday_year">
<option value="0">---</option>
<option value="1912">1912</option>
<option value="1913">1913</option>
<option value="1914">1914</option>
<option value="1915">1915</option>
<option value="1916">1916</option>
<option value="1917">1917</option>
<option value="1918">1918</option>
<option value="1919">1919</option>
<option value="1920">1920</option>
<option value="1921">1921</option>
<option value="1922">1922</option>
<option value="1923">1923</option>
<option value="1924">1924</option>
<option value="1925">1925</option>
<option value="1926">1926</option>
<option value="1927">1927</option>
<option value="1928">1928</option>
<option value="1929">1929</option>
<option value="1930">1930</option>
<option value="1931">1931</option>
<option value="1932">1932</option>
<option value="1933">1933</option>
<option value="1934">1934</option>
<option value="1935">1935</option>
<option value="1936">1936</option>
<option value="1937">1937</option>
<option value="1938">1938</option>
<option value="1939">1939</option>
<option value="1940">1940</option>
<option value="1941">1941</option>
<option value="1942">1942</option>
<option value="1943">1943</option>
<option value="1944">1944</option>
<option value="1945">1945</option>
<option value="1946">1946</option>
<option value="1947">1947</option>
<option value="1948">1948</option>
<option value="1949">1949</option>
<option value="1950">1950</option>
<option value="1951">1951</option>
<option value="1952">1952</option>
<option value="1953">1953</option>
<option value="1954">1954</option>
<option value="1955">1955</option>
<option value="1956">1956</option>
<option value="1957">1957</option>
<option value="1958">1958</option>
<option value="1959">1959</option>
<option value="1960">1960</option>
<option value="1961">1961</option>
<option value="1962">1962</option>
<option value="1963">1963</option>
<option value="1964">1964</option>
<option value="1965">1965</option>
<option value="1966">1966</option>
<option value="1967">1967</option>
<option value="1968">1968</option>
<option value="1969">1969</option>
<option value="1970">1970</option>
<option value="1971">1971</option>
<option value="1972">1972</option>
<option value="1973">1973</option>
<option value="1974">1974</option>
<option value="1975">1975</option>
<option value="1976">1976</option>
<option value="1977">1977</option>
<option value="1978">1978</option>
<option value="1979">1979</option>
<option value="1980">1980</option>
<option value="1981">1981</option>
<option value="1982">1982</option>
<option value="1983">1983</option>
<option value="1984">1984</option>
<option value="1985">1985</option>
<option value="1986">1986</option>
<option value="1987">1987</option>
<option value="1988">1988</option>
<option value="1989">1989</option>
<option value="1990">1990</option>
<option value="1991">1991</option>
<option value="1992">1992</option>
<option value="1993">1993</option>
<option value="1994">1994</option>
<option value="1995">1995</option>
<option value="1996">1996</option>
<option value="1997">1997</option>
<option value="1998">1998</option>
</select></span>
    </p>


    <p class="form-textarea">
        <label>Biography</label>
        <span><textarea id="id_biography" rows="10" cols="40" name="biography"></textarea></span>
    </p>


    <p class="form-text">
        <label>Website</label>
        <span><input autocapitalize="off" autocorrect="off" type="url" name="external_url" id="id_external_url" /></span>
    </p>


    <p class="form-actions"><input type="submit" class="button-green" value="Submit" /></p>

</form>


    <p class="remove-account"><a href="<?php echo BASEURL; ?>/accounts/remove/request/">I&#39;d like to delete my account</a></p>

            </section>
        </div> <!-- .main -->
    </div> <!-- .main -->


    </div> <!-- .page -->


    <footer class="page-footer">
        <div class="wrapper">
            <nav>
                <ul>
                    <li><a href="<?php echo BASEURL; ?>/accounts/edit/">Your Account</a></li>
                    <li><a href="<?php echo BASEURL; ?>/about/us/">About us</a></li>
                    <li><a href="http://help.instagram.com/">Support</a></li>
                    <li><a href="http://blog.instagram.com/">Blog</a></li>
                    <li><a href="<?php echo BASEURL; ?>/developer/">API</a></li>
                    <li><a href="<?php echo BASEURL; ?>/about/jobs/">Jobs</a></li>
                    <li><a href="<?php echo BASEURL; ?>/about/legal/privacy/">Privacy</a></li>
                    <li><a href="<?php echo BASEURL; ?>/about/legal/terms/">Terms</a></li>
                </ul>
            </nav>

            <p class="copyright">&copy; 2012 <?php echo SITE_NAME; ?></p>
        </div>
    </footer>

<?php if( @$_SESSION['SITE_DEBUG'] ): ?>
	<textarea style="width: 100%;" rows="50" cols="50" readonly="readonly">
	*** DEBUG ***
	------------------
	
	SESSION:
	------------------
	<?php print_r( $_SESSION ); ?>
	</textarea> 
<?php endif; ?>

</div> <!-- .root -->


</body>
</html>