window._strings = {

'Now': "ora",
'Couldn\'t post comment': "Impossibile postare il commento",
'Retry': "Riprova",
'Cancel': "Cancella",
'Add a comment': "Aggiungi un commento",
'Like': "Like",
'Likes': "Piace",
'No likes yet.': "Ancora nessun like.",
'%(user)s on Instagram': "%(user)s on Instagram",
'Follow': "Segui",
'%(count)s photos': "%(count)s foto",
'%(count)s following': "%(count)s seguendo",
'%(count)s followers': "%(count)s ti seguono",
'Following': "Seguendo",
'Load more...': "Carica altro...",
'Requested': "Richiesto",
'%(year)s %(month)s': "%(year)s %(month)s",
'%(day)s %(month_name)s %(year)s': "%(day)s %(month_name)s %(year)s",
'All items loaded': "Tutti gli elementi sono caricati.",
'Loading more...': "Loading more...",
'This user has no photos.': "This user has no photos.",
'Edit Profile': "Modifica Profilo",
'This user is private': "Questo profilo è privato",
'You need to be following %(username)s to like or comment': "Devi seguire %(username)s per mettere like e commentare",
'January': "gennaio",
'February': "febbraio",
'March': "marzo",
'April': "aprile",
'May': "maggio",
'June': "giugno",
'July': "luglio",
'August': "agosto",
'September': "settembre",
'October': "ottobre",
'November': "novembre",
'December': "dicembre",
'Select your badge:': "Select your badge:",
'Copy this code:': "Copy this code:",
'Paste it on your website, blog, or wherever you want to link to your profile!': "Paste it on your website, blog, or wherever you want to link to your profile!",
'1': "1",
'2': "2",
'3': "3"

}
;