window._strings = {

'Now': "Soeben",
'Couldn\'t post comment': "Konnte das Kommentar nicht posten",
'Retry': "Nochmal versuchen",
'Cancel': "Abbrechen",
'Add a comment': "Kommentiere",
'Like': "Like",
'Likes': "Likes",
'No likes yet.': "Gefällt noch keinem",
'%(user)s on Instagram': "%(user)s on Instagram",
'Follow': "Folgen",
'%(count)s photos': "%(count)s Fotos",
'%(count)s following': "%(count)s folge ich",
'%(count)s followers': "%(count)s Anhänger",
'Following': "Folge ich",
'Load more...': "Mehr laden...",
'Requested': "Angefordert",
'%(year)s %(month)s': "%(year)s %(month)s",
'%(day)s %(month_name)s %(year)s': "%(day)s %(month_name)s %(year)s",
'All items loaded': "Alle Einträge sind geladen",
'Loading more...': "Loading more...",
'This user has no photos.': "This user has no photos.",
'Edit Profile': "Profil ändern",
'This user is private': "Dieser Nutzer is privat.",
'You need to be following %(username)s to like or comment': "Du musst %(username)s folgen, um Kommentare und Feedback zu hinterlassen.",
'January': "Januar",
'February': "Februar",
'March': "März",
'April': "April",
'May': "Mai",
'June': "Juni",
'July': "Juli",
'August': "August",
'September': "September",
'October': "Oktober",
'November': "November",
'December': "Dezember",
'Select your badge:': "Select your badge:",
'Copy this code:': "Copy this code:",
'Paste it on your website, blog, or wherever you want to link to your profile!': "Paste it on your website, blog, or wherever you want to link to your profile!",
'1': "1",
'2': "2",
'3': "3"

}
;