<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Instagram</title>
        <meta name = "viewport" content = "width = 320px">
        <link rel="stylesheet" href="<?php echo BASEURL; ?>/static/styles/master-new.css?1" type="text/css" media="screen" title="no title" charset="utf-8">
</head>
<body>

    <div id="wrap" class="grid-all group">

<div style="width: 100%; margin: 0 auto;">
    <a href="<?php echo BASEURL; ?>">
        <img style="margin-left: 0em; margin-top: 1.0em;" src="<?php echo BASEURL; ?>/static/images/headerWithTitle.png"><br/>
    </a>
<?php echo $this->message ?>
</div>

    </div>
</body>
</html>